# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('date_expiration', models.DateField()),
                ('valide', models.BooleanField()),
                ('solde', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mdp', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mdp', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('mdp', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_employe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
                ('id_employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Employeur')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_commercant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Commercant')),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='id_employeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Employeur'),
        ),
        migrations.AddField(
            model_name='employe',
            name='num_carte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Carte'),
        ),
        migrations.AddField(
            model_name='carte',
            name='id_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Employe'),
        ),
    ]
