# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20170225_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='id_employe',
        ),
    ]
