# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_carte_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='num',
            field=models.IntegerField(unique=True),
        ),
    ]
